### ISSUE TITLE
Native tabbar

### ISSUE THREAD

**Issue by mark-kraemer** [hotwired/hotwire-native-ios#32]
I'm really excited about the release of Hotwire Native! I just tried it on a test project, and it was so simple to get up and running. I appreciate all the hard work you all put into making this experience better!
   
I've got multiple turbo ios and android apps and I'd love to leverage this release. Looking at the source code here, most of my turbo native ios app code can be removed as it's been moved inside this package. But there was one item that wasn't quite clear on how to move forward. Native tabbar - With my [previous implementation](https://gist.github.com/mark-kraemer/8986f0893b5410b153f265e3eb87ec31), I was able to load a native tabbar. but it failed to load the [content in the webview](https://gist.github.com/mark-kraemer/e77f381c81aa8e73200d820b7692821b) when I tried to reimplement this in Hotwire Native.

I think there is a need in the community for this and having an easy pattern people could use would be really awesome. I'm happy to help implement/test or make a PR request if we can figure out the right pattern

**Comment by yshmarov** [comment]
yes please!

**Comment by yshmarov** [comment]
I totally agree! Had the [same thought last night.](https://github.com/hotwired/hotwire-native-demo/issues/9) 

It would be very useful to have an out of the box example with tabs!

**Comment by MichalSznajder** [comment]
I think there are two approaches.

One is to use `UITabBarController` and embedded `Navigator` for each tab. This results in separate WebView and separate cold boot for each tab. Each tab maintains its own context and state.

Another option is to make custom UIController, put `UITabBar` at the bottom and `Navigator` at top. Than hide tab bar depending where you navigate.

**Comment by olivaresf** [comment]
Hey @mark-kraemer,

> One option is to use a UITabBarController with a separate embedded UINavigationController for each tab. This creates independent WebView instances for each tab, resulting in a separate cold boot and allowing each tab to maintain its own context and state.

Like @MichalSznajder mentioned, this is our current approach. It works well in Basecamp, although you have to be careful not to instantiate all webviews at app launch or else your app may hang for a few seconds. 

Joe Massillotti has wrote about this approach here: https://masilotti.com/turbo-native-tabs/. Since Hotwire Native absorbed a big chunk of Joe's own Turbo Navigator, that tutorial should give you a good idea of how the actual implementation goes.

If you have any other feature requests, we also monitor the Hotwire forums here: https://discuss.hotwired.dev. For now, I'll be closing this issue.

Thanks!

**Comment by yshmarov** [comment]
here's what works for me on top of the Demo app

```diff
# Demo/SceneController.swift
final class SceneController: UIResponder {
    var window: UIWindow?

    private let rootURL = Demo.current
-    private lazy var navigator = Navigator(pathConfiguration: pathConfiguration, delegate: self)
+    private lazy var navigators: [Navigator] = {
+        (0..<3).map { _ in Navigator(pathConfiguration: pathConfiguration, delegate: self) }
+    }()
+    private lazy var tabBarController = TabBarController(navigators: navigators)

...

+class TabBarController: UITabBarController {
+    private let navigators: [Navigator]
+    
+    init(navigators: [Navigator]) {
+        self.navigators = navigators
+        super.init(nibName: nil, bundle: nil)
+        
+        viewControllers = navigators.map { $0.rootViewController }
+        
+        // Customize tab bar items
+        viewControllers?[0].tabBarItem = UITabBarItem(title: "Home", image: UIImage(systemName: "house"), tag: 0)
+        viewControllers?[1].tabBarItem = UITabBarItem(title: "Posts", image: UIImage(systemName: "play.circle"), tag: 1)
+        viewControllers?[2].tabBarItem = UITabBarItem(title: "Playlists", image: UIImage(systemName: "list.number"), tag: 2)
+    }
+    
+    required init?(coder: NSCoder) {
+        fatalError("init(coder:) has not been implemented")
+    }
+}
```

Result - each footer tab has it's own navigation, as expected; the default UITabBarItem titles are overridden with the HTML `<title>` -> works as expected:

<img width="464" alt="Screenshot 2024-10-04 at 12 04 43" src="https://github.com/user-attachments/assets/6410a561-bec1-4309-b219-602c9cf8d8b2">

To make the tab bar not transparent:

```swift
extension UITabBar {
    static func configureWithOpaqueBackground() {
        let tabBarAppearance = UITabBarAppearance()
        tabBarAppearance.configureWithOpaqueBackground()
        
        // tabBarAppearance.backgroundColor = .systemGray5
        // https://www.uicolor.io/ - transform hex into swift
        tabBarAppearance.backgroundColor = UIColor(red: 0.09, green: 0.11, blue: 0.13, alpha: 1.00)
        
        appearance().standardAppearance = tabBarAppearance
        appearance().scrollEdgeAppearance = tabBarAppearance
    }
}
```

& add
```diff
    private func configureRootViewController() {
        guard let window = window else {
            fatalError()
        }
        
+        UITabBar.configureWithOpaqueBackground()
        
        window.rootViewController = tabBarController
    }
```

Perfecto! 👏👏👏

**Comment by ibrahima** [comment]
> the default UITabBarItem titles are overridden with the HTML `<title>` -> works as expected:

Hi! I've looked at your guide which is great, but I'm wondering if there's a way to disable this behavior. I feel like it would be nice to just hardcode it for now.

**Comment by yshmarov** [comment]
> > the default UITabBarItem titles are overridden with the HTML `<title>` -> works as expected:
> 
> Hi! I've looked at your guide which is great, but I'm wondering if there's a way to disable this behavior. I feel like it would be nice to just hardcode it for now.

what's the problem? just set the same static <title> in all your hmtl pages

**Comment by ibrahima** [comment]
It looks like maybe tabs are coming to the demo app? 🎉

One point I wanted to mention - I don't know if anyone else has run into this, but when I set up navigation tabs in my app without lazy loading, I got an issue where the CSRF tokens are invalid for all but the last tab. If you reload the tabs or submit once and get an error, subsequent submits will work correctly. I figured lazy loading the tabs is better for performance anyway so I implemented it on my app. But I just wanted to mention this in case anyone else runs into this issue.

I think this happens because [Rails generates a CSRF token and stores it in the browser session if one is not already set](https://github.com/rails/rails/blob/801959745469e3ab2ad48ba3f2191f68792e7def/actionpack/lib/action_controller/metal/request_forgery_protection.rb#L577), so if you load multiple tabs simultaneously at the start of your app and nothing is in the browser session yet, you'll get a race condition with the last tab "winning" and being the only one with a valid CSRF token.

(technically it might store it in someplace other than the browser session but I think that's the default)
